name: "op-cli-login-action"
description: "Configures account and signs in to 1Password"
inputs:
  username:
    description: Account username
    required: true
  password:
    description: Account password
    required: true
  secretKey:
    description: Account secret key
    required: true
  domain:
    description: Account domain
    required: true
outputs:
  sessionToken:
    description: Session id returned by login
    value: ${{ steps.login.outputs.token }}
runs:
  using: "composite"
  steps:
    - id: login
      run: |
        export OP_DEVICE=iyr6wvn5qf63xquqf7howqlxsa
        echo "${{ inputs.password }}" | op account add \
          --address "${{ inputs.domain }}" \
          --email "${{ inputs.username }}" \
          --secret-key "${{ inputs.secretKey }}"
        tokenCmd=$(echo "${{ inputs.password }}" | op signin --raw)
        echo "::add-mask::$tokenCmd"
        echo "::set-output name=token::$tokenCmd"
      shell: bash

