name: Release new version

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: 'Release package'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com

      - name: 'Setup cache for node_modules'
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: 'Prepare git'
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "github version update"
          git branch -u origin/main main

      - name: 'Install project'
        run: yarn install

      - name: 'Increase version and push to git'
        run: |
          yarn release
          git push --follow-tags

      - name: 'Publish release to npm'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
